### ISSUE TITLE
zhfonts.py does not work with Python 3.4

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#131]
It is reported at `zhfonts.py` does not work with Python 3.4

**Comment by yangsheng6810** [comment]
This is error message come from running zhfonts.py with Python 3.4
```
Traceback (most recent call last):
  File "./zhfonts.py", line 179, in <module>
    line = line.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```
The problem arise only for manipulating ``shuji.tex'', other things works fine. I do not have Python 3.3 installed, so I cannot test whether it works on Python 3.3. But Python 2.7 works.

After googling, I find that this may b3e caused by the difference in handling input between Python 2 and Python 3, an explanation and solution(not so good) can be find here [http://python3porting.com](http://python3porting.com/problems.html), in the section ``Reading from files''.

Hop that will help.

**Comment by alick** [comment]
The issue lies in python 2/3 compatibility. cf. http://www.zopatista.com/python/2013/11/26/inplace-file-rewriting/

**Comment by alick** [comment]
Although the current fix is very ugly, I think the solution in the above link is overkill for our small script.

**Comment by alick** [comment]
Please let me know if you have better ideas.

FYI, inplace and encoding hook cannot be used at the same time as I tried...

**Comment by yangsheng6810** [comment]
Confirm working for Python 3.4.3 and Python 2.7.9.
